services:
  telegram_bot:
    ports:
      - 8443:8443
    build:
      context: .
      dockerfile: bot/Dockerfile
    command: python -m bot.main
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  fastapi_webapp:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: webapp/Dockerfile
    volumes:
      - .:/app
    command: uvicorn webapp.main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  fastapi_admin:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: admin/Dockerfile
    volumes:
      - .:/app
    command: uvicorn admin.main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/gamebot/certificate.crt:/home/gamebot/certificate.crt
      - /home/gamebot/certificate.key:/home/gamebot/certificate.key
    depends_on:
      - fastapi_webapp

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  
volumes:
  postgres_data: