services:
  telegram_bot:
    ports:
      - 8443:8443
    build:
      context: .
      dockerfile: bot/Dockerfile
    command: python -m bot.main
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - netweb

  fastapi_webapp:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: webapp/Dockerfile
    volumes:
      - .:/app
    command: uvicorn webapp.main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - netweb

  fastapi_admin:
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: admin/Dockerfile
    volumes:
      - .:/app
    command: uvicorn admin.main:app --host 0.0.0.0 --port 5000
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - netweb
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/gamebot/certificate.crt:/home/gamebot/certificate.crt
      - /home/gamebot/certificate.key:/home/gamebot/certificate.key
    networks:
      - netweb

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qfokdsjihf123131SHJJQW
      POSTGRES_DB: postgres
    networks:
      - netweb
  
volumes:
  postgres_data:

networks:
  netweb:
    external: true
